### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by dandevelop** [sciter-sdk/go-sciter#69]
Running the callback sample.

Every time I hit the Click Me button memory usage goes up and it keeps adding every time I click the Click Me button. 

Any ideas what might be causing this?

**Comment by dandevelop** [comment]
Looks like an issue with Sciter. Will report it there.

**Comment by pravic** [comment]
OS? Screenshots? Have you tried to reduce code to find the source of the leak?

I wrote similar code in Python, which uses the same html, and I could not see any leaks between clicks.
But if I comment out message box and press button more frequently, the memory will be raised a bit. But may be it is due to message queue (event queue in Sciter). It is like 0.1mb from 20 or so clicks.

**Comment by dandevelop** [comment]
It looks like it is related to the messagebox. Here is the code that I ended up with:

```
<html>
<head>
<script type="text/tiscript">
$(#btn).on("click",function(){
    view.msgbox(#information,"Hello");
});
</script>
</head>
<body>
<div>
    <button id="btn">Click Me</button>
</div>
</body>
</html
```

This causes the memory usage to increase. This is on macOS.

**Comment by pravic** [comment]
Yeah, it happens even on Windows with Sciter.exe app. Several times memory returns back after message box disappears, but from time to time it increases.
